#!/usr/bin/env bash
# Isolated full-stack e2e lane for a checkout/worktree.
#
#   scripts/agent-stack.sh up        # build + start Temporal, api, worker
#   scripts/agent-stack.sh test      # smoke checks against the running stack
#   scripts/agent-stack.sh logs [s]  # tail logs (all services or one)
#   scripts/agent-stack.sh url       # print the stack's URLs
#   scripts/agent-stack.sh down      # stop + remove containers, network, volume
#
# Isolation model: compose project name + image tag derive from the worktree
# directory name; published ports are docker-assigned ephemeral; sqlite lives
# in the project volume removed by `down`. Two worktrees can run stacks
# concurrently. This script never touches ghost or any shared infra.
set -euo pipefail

REPO_ROOT="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
cd "$REPO_ROOT"

COMPOSE_FILE="docker-compose.stack.yml"
ENV_FILE=".env.stack"

# Project/image slug = worktree dir name (sanitized). In the main checkout it
# is 'soonish'; in ../notifiq-worktrees/<name> it is '<name>'. CI runs share
# the DinD daemon, so GITHUB_RUN_ID keeps concurrent jobs' projects distinct.
SLUG="$(basename "$REPO_ROOT" | tr '[:upper:]' '[:lower:]' | tr -d '\n' | tr -c 'a-z0-9-' '-' | sed 's/-*$//')"
[ -n "${GITHUB_RUN_ID:-}" ] && SLUG="${SLUG}-ci${GITHUB_RUN_ID}"
PROJECT="notifiq-e2e-${SLUG}"
export STACK_IMAGE="notifiq-e2e-${SLUG}"
export STACK_ENV_FILE="$ENV_FILE"

# Where published ports are reachable. Locally that's localhost; in CI the
# daemon is the DinD service container, so ports bind STACK_BIND (0.0.0.0)
# and are reached via the daemon hostname (docker-in-docker).
STACK_HOST="${STACK_HOST:-localhost}"

compose() {
    docker compose -f "$COMPOSE_FILE" -p "$PROJECT" "$@"
}

api_port() {
    # Last colon-field: handles "127.0.0.1:P", "0.0.0.0:P" and "[::]:P".
    compose port api 8000 2>/dev/null | awk -F: '{print $NF}'
}

api_url() {
    echo "http://${STACK_HOST}:$(api_port)"
}

generate_env() {
    # Idempotent: keep an existing env so down/test find the same stack.
    [ -f "$ENV_FILE" ] && return
    python3 - "$ENV_FILE" <<'PY'
import base64, os, secrets, sys
with open(sys.argv[1], "w") as f:
    f.write("# Generated by scripts/agent-stack.sh — ephemeral, disposable.\n")
    f.write("# Never commit (.env.* is gitignored).\n")
    f.write("DEBUG=true\n")
    f.write("DEV_MODE=true\n")
    f.write(f"ENCRYPTION_KEY={base64.urlsafe_b64encode(os.urandom(32)).decode()}\n")
    f.write(f"SECRET_KEY={secrets.token_urlsafe(32)}\n")
    f.write("ADMIN_EMAILS=admin@example.com\n")
    f.write("API_BASE_URL=http://localhost:8000\n")
    f.write("FRONTEND_BASE_URL=http://localhost:8000\n")
    f.write('CORS_ORIGINS=["http://localhost:8000","http://127.0.0.1:8000"]\n')
    f.write("COOKIE_SECURE=false\n")
    f.write("COOKIE_SAMESITE=lax\n")
    f.write("TRUST_PROXY_HEADERS=false\n")
    f.write("BILLING_ENABLED=false\n")
    f.write("LOG_LEVEL=INFO\n")
    f.write("OTEL_ENABLED=false\n")
PY
}

cmd_up() {
    generate_env
    echo "==> docker compose up (project: $PROJECT, image: $STACK_IMAGE)"
    compose up -d --build

    echo "==> waiting for api health"
    port="$(api_port)"
    [ -n "$port" ] || { echo "FAIL: api has no published port" >&2; exit 1; }
    url="http://${STACK_HOST}:$port"
    for _ in $(seq 1 60); do
        if curl -sf --max-time 5 "$url/api/v1/health" >/dev/null 2>&1; then
            echo "==> stack is UP"
            cmd_url
            return
        fi
        sleep 2
    done
    echo "FAIL: api did not become healthy in 120s" >&2
    compose ps >&2
    exit 1
}

cmd_down() {
    local keep_image="${1:-}"
    compose down -v --remove-orphans
    rm -f "$ENV_FILE"
    if [ "$keep_image" != "--keep-image" ]; then
        docker rmi "$STACK_IMAGE" >/dev/null 2>&1 || true
    fi
    echo "==> stack $PROJECT removed (containers, network, volume)"
}

cmd_test() {
    local base url failures=0
    base="$(api_url)"
    check() {
        local label="$1" path="$2" code
        code="$(curl -s --max-time 10 -o /dev/null -w '%{http_code}' "$base$path")"
        if [ "$code" = "200" ]; then
            echo "  PASS  $label ($path -> $code)"
        else
            echo "  FAIL  $label ($path -> $code)"
            failures=$((failures + 1))
        fi
    }
    echo "==> smoke test against $base"
    check "health"        "/api/v1/health"
    check "front door"    "/"
    check "api docs"      "/docs"
    for mount in mission-control volunteer-coordinator event-planner duty-pager \
                 developer-user tasks stage-manager adhd-reminders mindful; do
        check "spa:$mount" "/$mount/"
    done
    echo "==> $failures failure(s)"
    [ "$failures" -eq 0 ]
}

cmd_url() {
    local api ui grpc
    api="$(api_port)"
    ui="$(compose port temporal 8233 2>/dev/null | awk -F: '{print $NF}')"
    grpc="$(compose port temporal 7233 2>/dev/null | awk -F: '{print $NF}')"
    echo "app:          http://${STACK_HOST}:$api"
    echo "api/docs:     http://${STACK_HOST}:$api/docs"
    echo "temporal ui:  http://${STACK_HOST}:$ui"
    echo "temporal rpc: ${STACK_HOST}:$grpc"
    echo "project:      $PROJECT   image: $STACK_IMAGE"
}

case "${1:-}" in
    up)    cmd_up ;;
    down)  cmd_down "${2:-}" ;;
    test|smoke) cmd_test ;;
    url)   cmd_url ;;
    logs)  compose logs -f "${2:-}" ;;
    ps)    compose ps ;;
    exec)  shift; compose exec "$@" ;;
    "")    echo "usage: agent-stack.sh {up|down|test|url|logs|ps|exec}" >&2; exit 2 ;;
    *)     echo "unknown command: $1" >&2; exit 2 ;;
esac
