#!/usr/bin/env bash
# Bootstrap an isolated git worktree for an agent to work + verify in.
#
#   scripts/agent-worktree.sh <name> [base-ref]
#
# Creates ../notifiq-worktrees/<name> on branch agent/<name>, writes a
# backend/.env with ephemeral secrets, a LOCAL Temporal URL and a task queue
# unique to the worktree, then `uv sync`s the backend.
#
# This script never points anything at ghost:7233 (shared PROD Temporal).
set -euo pipefail

NAME="${1:-}"
BASE_REF="${2:-main}"
if [ -z "$NAME" ]; then
    echo "usage: scripts/agent-worktree.sh <name> [base-ref]" >&2
    exit 2
fi
case "$NAME" in
    *[!a-zA-Z0-9._-]*) echo "name must be [a-zA-Z0-9._-] only (it becomes a branch + task queue)" >&2; exit 2 ;;
esac

# Resolve the main checkout even if we're invoked from inside another worktree.
REPO_ROOT="$(git -C "$(dirname "$0")" rev-parse --path-format=absolute --git-common-dir)"
REPO_ROOT="$(cd "$(dirname "$REPO_ROOT")" && pwd)"
WORKTREE_PARENT="$(dirname "$REPO_ROOT")/notifiq-worktrees"
WORKTREE="$WORKTREE_PARENT/$NAME"
BRANCH="agent/$NAME"
TASK_QUEUE="notifiq-wt-$NAME"

if [ -e "$WORKTREE" ]; then
    echo "$WORKTREE already exists — pick another name or remove it:" >&2
    echo "  git -C '$REPO_ROOT' worktree remove '$WORKTREE'" >&2
    exit 1
fi

echo "==> git worktree add $WORKTREE ($BRANCH from $BASE_REF)"
mkdir -p "$WORKTREE_PARENT"
git -C "$REPO_ROOT" worktree add -b "$BRANCH" "$WORKTREE" "$BASE_REF"

echo "==> uv sync (backend)"
( cd "$WORKTREE/backend" && uv sync )

echo "==> writing $WORKTREE/backend/.env (ephemeral secrets, local Temporal)"
ENCRYPTION_KEY="$(cd "$WORKTREE/backend" && uv run python -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())')"
SECRET_KEY="$(cd "$WORKTREE/backend" && uv run python -c 'import secrets; print(secrets.token_urlsafe(32))')"

cat > "$WORKTREE/backend/.env" <<EOF
# Generated by scripts/agent-worktree.sh for worktree '$NAME'.
# Ephemeral + disposable. Never commit (.env is gitignored).

DEBUG=true
DEV_MODE=true

ENCRYPTION_KEY=$ENCRYPTION_KEY
SECRET_KEY=$SECRET_KEY

# LOCAL temporal only. ghost:7233 is shared PROD — do not point this there.
TEMPORAL_URL=localhost:7233
TEMPORAL_NAMESPACE=default
# Unique per worktree so concurrent agents never consume each other's tasks.
TEMPORAL_TASK_QUEUE=$TASK_QUEUE

# sqlite is relative to backend/, so this db is private to this worktree.
DATABASE_URL=sqlite+aiosqlite:///notifiq.db

ADMIN_EMAILS=admin@example.com
EOF

# Safety net: no setting (comments excluded) may address prod Temporal.
if grep -v '^[[:space:]]*#' "$WORKTREE/backend/.env" | grep -qi 'ghost'; then
    echo "ABORT: generated .env points at ghost — refusing to leave it in place" >&2
    rm -f "$WORKTREE/backend/.env"
    exit 1
fi

cat <<EOF

==> Worktree ready.

  cd $WORKTREE
  just verify                 # the baseline proof (backend + all frontends)
  VERIFY_FRONTENDS=frontend-website just verify   # faster subset

  Temporal:     localhost:7233 (start your own: temporal server start-dev)
  Task queue:   $TASK_QUEUE
  Branch:       $BRANCH

Before you open a PR:
  just proof-init             # proof/<branch-slug>.md from the template
  ./scripts/proof exec bash "<command that proves your change>"
  just proof-verify           # appends the baseline 'just verify' output
  git add proof/ && git commit
  just proof-check            # the same gate CI applies to the PR

Clean up later:
  git -C $REPO_ROOT worktree remove $WORKTREE
EOF
